name: ⚙️ Continuous update 📦

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" #At 00:00 UTC on Sunday every Week

jobs:
  update_rebuild_and_release:
    name: lwrun-update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
          filter: "blob:none"

      - name: Install deps
        run: |
          sudo sh -c 'apt update && apt install zsync -y'
          sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns <<<0

      - name: Bootstrap RunImage
        run: |
            set -x ; set -e
            mkdir -p release && cd release||exit 1

            curl -LO https://github.com/VHSgunzo/lwrun/releases/download/continuous/lwrun
            chmod +x lwrun
            ./lwrun --runtime-extract
            rm -f lwrun
            ./RunDir/Run rim-update
            ./RunDir/Run rim-shrink -a
            ./RunDir/Run rim-pkgls > pkg_list-lwrun.txt
            ./RunDir/Run rim-build -d -b 18 -z -c 22 lwrun
            chmod u+rw -R RunDir && rm -rf RunDir
            sha256sum_lwrun="$(sha256sum lwrun)"
            zsyncmake lwrun

            echo "\
            -----------------------------------------------------------------------------------------------------------------------------
            * [lwrun](https://github.com/VHSgunzo/lwrun/releases/download/continuous/lwrun) | [pkg_list-lwrun.txt](https://github.com/VHSgunzo/lwrun/releases/download/continuous/pkg_list-lwrun.txt)
            -----------------------------------------------------------------------------------------------------------------------------
            ## sha256sum:
            \`\`\`
            ${sha256sum_lwrun}
            \`\`\`" > ../RELEASE_NOTE.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "continuous"
          prerelease: false
          draft: false
          body_path: "RELEASE_NOTE.md"
          files: release/*
